export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const RESENT_CONFIRM_MAIL = 'RESENT_CONFIRM_MAIL';
export const UPDATE_CART_ITEMS_COUNT = 'UPDATE_CART_ITEMS_COUNT';